name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make
    - name: Run tests
      run: ./test.sh
